name: release

on:
  push:

jobs:
  build:
    name: build-windows
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive
          
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: NuGet Restore
      run: |
        cd ${{ github.workspace }}
        nuget restore RoundedTB.sln
      
    - name: Build
      run: |
        cd ${{ github.workspace }}
        msbuild "-property:Configuration=Release" -t:RoundedTB

    - name: Add commit hash to output folder
      run: |
        Rename-Item -Path ".\RoundedTB\bin\Release" -NewName "RoundedTB-$(git rev-parse --short ${{ github.sha }})"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rtb-artifacts
        path: |
          .\RoundedTB\bin\RoundedTB-*\
